name: MISRA Check
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install cppcheck
      - name: Checkout tests repository
        uses: actions/checkout@v4
        with:
          repository: feaser/microtbx-tests
          submodules: true
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'third_party/microtbx'
      - name: Generate build environment
        working-directory: build
        run: cmake ..
      - name: Perform MISRA compliance check
        working-directory: build/tests/base/LINUX_PC
        run: make microtbx_MISRA

